/**************************
**Program:		Conf_To_PDB.c
**Description:	Trans the conf.dat generated by DNAfold into .pdb file
**Author:		YZ Shi
**Date:		2023.7
**Compile:	gcc -Wall -o3 Conf_To_PDB.c -o CTP -lm
**Run:		./CTP &RNA_length
***************************/
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#define max_conf 20000
#define max_atom 1000

float top=0.25;
float x_c[max_conf][max_atom],y_c[max_conf][max_atom],z_c[max_conf][max_atom],R_c[max_conf][max_atom];
int   N,N0,num_CG[max_conf][max_atom],conf_start;
char  type[max_atom],type_CG[max_conf][max_atom];
/*********************************************************************************/
int main(int argc, char *argv[])
{
 void  Read_Conf();
 clock_t start,end;
 start=clock();
 printf("Trans the conf.dat into pdb file\n");  
 if (argc<2) {printf("run like: ./CTP &RNA_length (nt) or ./CTP &RNA_length &conf_start\n");}
 else if (argc==2) {conf_start=1;}
 else {conf_start=atoi(argv[2]);}
 N=atoi(argv[1]);
 N0=3*N+1;

 Read_Conf();
 end = clock();
 float spendtime = (float)(end-start)/(CLOCKS_PER_SEC);
 printf("Finished with the spendtime of %f s.\n",spendtime);
 return 0;
}
/************************Calculation of our predicted conformation****************************/
void Read_Conf()
{  
 int   i,duo1;
 float Q_c,f_c;
 //float xx[max_atom],yy[max_atom],zz[max_atom];
 char  filename[20];
 FILE *inconf,*out_conf_pdb;
 int j=1; 
 sprintf(filename,"results/conf.dat"); inconf=fopen(filename,"r+");  //conformation
 i=1;  
 while(!feof(inconf)) {         
      fscanf(inconf,"%d %d %c %f %f %f %f %f %f\n",&duo1,&num_CG[j][i],&type_CG[j][i],&x_c[j][i],&y_c[j][i],&z_c[j][i],&R_c[j][i],&Q_c,&f_c); 
      if (fmod(i,N0)==0) {
          if (num_CG[j][i]!=i) {printf("Error: Read faied (i=%d num_CG=%d)\n",i,num_CG[j][i]); exit(1);} 
          j++; i=0;}
      i++;} 
 int num_conf=j-1;    
 if (num_conf>=max_conf) {
    printf("Error: you provide too much conformations (e.g., %d > max_conf)\n",num_conf); exit(0);}
 printf("Number of conformation: %d (number of atom in each conf.: %d)\n",num_conf,N0);
 fclose(inconf);    //input of the initial conformation 
  
 out_conf_pdb=fopen("results/conf.pdb","w+"); 
 char  atom_name[10],res_name,chain='A';
 for (j=1;j<=num_conf;j++) {
     if (j>=conf_start) {
        int l=0;
        float x_middle=0.,y_middle=0.,z_middle=0.;
        fprintf(out_conf_pdb,"CRYST1    %d\n",j);
        for (i=1;i<=N0;i++)   {x_middle += x_c[j][i]; y_middle += y_c[j][i]; z_middle += z_c[j][i];}
        for (i=1;i<N0;i++)   {
            x_c[j][i]-=x_middle/N0;y_c[j][i]-=y_middle/N0;z_c[j][i]-=z_middle/N0;
            if (fmod(i+2,3)==0) {l++; strcpy(atom_name,"P");  res_name=type_CG[j][i+2];}
            else if (fmod(i+1,3)==0) {strcpy(atom_name,"C4'");res_name=type_CG[j][i+1];}
            else { res_name=type_CG[j][i];
               if (type_CG[j][i]=='G'||type_CG[j][i]=='A') {strcpy(atom_name,"N9");}
               else {strcpy(atom_name,"N1");}}
            fprintf(out_conf_pdb,"%s  %5d  %-4s  %c %c%4d    %8.3f%8.3f%8.3f\n","ATOM",i,atom_name,res_name,chain,l,x_c[j][i],y_c[j][i],z_c[j][i]);
       }
       fprintf(out_conf_pdb,"END\n");
    }
 }
 fclose(out_conf_pdb); 
}
